<table class="table table-striped">
	<thead class="thead-dark">
	<tr>
		<th scope="col">Scan Start URL</th>
		<th scope="col">Date</th>
		<th scope="col">Pages Crawled</th>
		<th scope="col">Unique Internal Links</th>
		<th scope="col">Unique External Links</th>
		<th scope="col">Unique Images</th>
	</tr>
	</thead>
	<tbody>
	<?php foreach ( $scans as $scan ) : ?>
		<tr>
			<th scope="row"><a href='scan/show/<?php echo $scan->id; ?>'><?php echo $scan->base_url; ?></a></th>
			<td><?php echo date( 'D M j', strtotime( $scan->timestamp ) ); ?></td>
			<td><?php echo $scan->pages_scanned; ?></td>
			<td><?php echo $scan->internal_links; ?></td>
			<td><?php echo $scan->external_links; ?></td>
			<td><?php echo $scan->images; ?></td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>