<h1>New Scan</h1>
<form method='post'>
	<div class="form-group">
		<label for="url">Scan URL</label>
		<?php
		if ( ! empty( $messages ) && ! empty( $messages->filter( 'url' ) ) ) {
			echo $form->render( 'url', [ 'class' => 'form-control is-invalid' ] );
			foreach ( $messages->filter( ( 'url' ) ) as $message ) {
				echo "<div class='invalid-feedback'>{$message}</div>";
			}
		} else {
			echo $form->render( 'url' );
		}
		?>
	</div>
	<div class="form-group">
		<label for="max_pages">Max pages to scan</label>
		<?php
		if ( ! empty( $messages ) && ! empty( $messages->filter( 'max_pages' ) ) ) {
			echo $form->render( 'max_pages', [ 'class' => 'form-control is-invalid' ] );
			foreach ( $messages->filter( ( 'max_pages' ) ) as $message ) {
				echo "<div class='invalid-feedback'>{$message}</div>";
			}
		} else {
			echo $form->render( 'max_pages' );
		}
		?>
	</div>
	<p><input class="btn btn-success" type='submit' value='Start Scan'/></p>
</form>